# Generated by Django 5.0.6 on 2024-06-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(null=True)),
                ('na_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eu_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jp_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('global_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data_load.genre')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data_load.platform')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data_load.publisher')),
            ],
        ),
    ]
