# Generated by Django 5.0.6 on 2024-06-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_load', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='eu_sales',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='global_sales',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='jp_sales',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='na_sales',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='other_sales',
            field=models.FloatField(),
        ),
    ]
